---
title: "New York City Vehicle Accidents"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill

---


```{r setup, include=FALSE}
library(shiny)
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(jsonlite)
library(plotly)
library(DT)
library(shinythemes)
library(httr)
library(htmltools)
library(sf)
library(rgdal)
library(leaflet)
library(leaflet.extras)


# #to install pacakgs while working on school computers
# install.packages(c("shiny", "flexdashboard", "tidyverse", "jsonlite", "plotly", "DT", "shinythemes", "httr", "htmltools", "sf", "rgdal", "leaflet", "leaflet.extras"), dependencies = TRUE)


#API Documentation: https://dev.socrata.com/foundry/data.cityofnewyork.us/qiz3-axqb

#Defining API functions from class
ckanGeoSQL <- function(url) {
  # Make the Request
  r <- RETRY("GET", URLencode(url))
  # Extract Content
  c <- content(r, "text")
  # Basic gsub to make NA's consistent with R
  json <- gsub('NaN', 'NA', c, perl = TRUE)
  # Create Dataframe
  readOGR(json)
}

ckanSQL <- function(url) {
  # Make the Request
  r <- RETRY("GET", URLencode(url))
  # Extract Content
  c <- content(r, "text")
  # Basic gsub to make NA's consistent with R
  json <- gsub('NaN', 'NA', c, perl = TRUE)
  # Create Dataframe
  data.frame(fromJSON(json))
}


 # Unique values for Resource Field
 ckanUniques <- function(type, field) {
   if (type == "text") {
      url <- paste0("https://data.cityofnewyork.us/resource/qiz3-axqb.geojson?$select=lower(",field,")&$group=",field,"&$having=",field," IS NOT NULL")
   }
   if (type == "num") {
      url <- paste0("https://data.cityofnewyork.us/resource/qiz3-axqb.geojson?$select=",field,"&$group=",field,"&$having=",field," IS NOT NULL")
   }
   print(url)
   c(ckanSQL(URLencode(url)))
 }
 
# test1 <- ckanUniques(field = "vehicle_type_code1")
# 
# test2 <- ckanUniques(field = "contributing_factor_vehicle_1")




# url <- "https://data.cityofnewyork.us/resource/qiz3-axqb.geojson?$limit=10000"
# accidents.load <- ckanGeoSQL(url = url)
# accidents.load$date <- as.Date(accidents.load$date)
# accidents.load$vehicle_type_code1 <- tolower(accidents.load$vehicle_type_code1)
# 
# # url2 <- "https://data.cityofnewyork.us/resource/qiz3-axqb.geojson?$select=lower(vehicle_type_code1)&$group=vehicle_type_code1&$having=vehicle_type_code1= IS NOT NULL"
# # accidents.uniq <- ckanSQL(url = url2)

```

Sidebar {.sidebar}
=====================================

```{r}
    output$CarType <- renderUI({
    selectInput(inputId = "factorType1",
                   label = "Step 1: Choose a Contributing Factor",
                   choices = ckanUniques(type = "text", field = "contributing_factor_vehicle_1")$features.properties$lower_contributing_factor_vehicle_1 ,
                   multiple = TRUE,
                   selectize = TRUE,
                   selected = ckanUniques(type = "text", field = "contributing_factor_vehicle_1")$features.properties$lower_contributing_factor_vehicle_1[1]
                   )
    })
uiOutput("CarType")


AccidInput.Init <- reactive({
   url <- paste0("https://data.cityofnewyork.us/resource/qiz3-axqb.geojson?$where=lower(contributing_factor_vehicle_1) in('",noquote(paste(input$factorType1, collapse = "', '")),"')")
    print(url)
    print(noquote(paste(input$factorType1, collapse = "', '")))
    accidents.serverA <- ckanGeoSQL(url = url)
    accidents.serverA$date <- as.Date(accidents.serverA$date)
    accidents.serverA$number_of_motorist_injured <- as.numeric(as.character(accidents.serverA$number_of_motorist_injured))
    accidents.serverA$number_of_pedestrians_injured <- as.numeric(as.character(accidents.serverA$number_of_pedestrians_injured))
   return(accidents.serverA)
  })


AccidInput <- reactive({
    accidents.server1 <- AccidInput.Init()
     if (!is.null(input$dateRange1)) {
      accidents.server1@data <- accidents.server1@data %>% 
        filter(date >= input$dateRange1[1] & date <= input$dateRange1[2])
      print("filter date")
    }
    if (!is.null(input$numInjurM1)) {
      accidents.server1@data <- accidents.server1@data %>% 
        filter(number_of_motorist_injured <= input$numInjurM1) 
      print("filterm1")
    }
    if (!is.null(input$numInjurP1)) {
      accidents.server1@data <- accidents.server1@data %>% 
        filter(number_of_pedestrians_injured <= input$numInjurP1) 
      print("filterp1")
    }
    

  return(accidents.server1)
  })

output$dateRange <- renderUI({
    dateRangeInput(inputId = "dateRange1",
                   label = "Step 2: Pick a Date Range",
                   start = min(AccidInput()$date, na.rm = TRUE), 
                   end = max(AccidInput()$date, na.rm = TRUE),
                   min = min(AccidInput.Init()$date, na.rm = TRUE),
                   max = max(AccidInput.Init()$date, na.rm = TRUE)
                   )
    })
uiOutput("dateRange")

output$numInjurM <- renderUI({
        sliderInput(inputId = "numInjurM1", 
                    label = "Step 3: Choose the Maximum Number of Injured Drivers",
                    min = min(AccidInput.Init()$number_of_motorist_injured, na.rm = TRUE), 
                    max = max(AccidInput.Init()$number_of_motorist_injured, na.rm = TRUE),
                    value = max(AccidInput()$number_of_motorist_injured, na.rm = TRUE))
    })
uiOutput("numInjurM")

output$numInjurP <- renderUI({
        sliderInput(inputId = "numInjurP1", 
                    label = "Step 4: Choose the Maximum Number of Injured Pedestrians",
                    min = min(AccidInput.Init()$number_of_pedestrians_injured, na.rm = TRUE), 
                    max = max(AccidInput.Init()$number_of_pedestrians_injured, na.rm = TRUE),
                    value = max(AccidInput()$number_of_pedestrians_injured, na.rm = TRUE))
    })
uiOutput("numInjurP")




## Download Button
renderUI({downloadButton('downloadFile','Download Raw Data')})

output$downloadFile <- downloadHandler(filename = function() {
     paste("Accident_Data-", Sys.Date(), ".csv", sep="")
   },
     content = function(file) {
     write.csv(subset(AccidInput()@data, select = c(date, time, borough, latitude, longitude,contributing_factor_vehicle_1, number_of_motorist_injured, number_of_cyclist_killed, number_of_pedestrians_killed, number_of_motorist_killed)), file)
   }
)

```


```{r include=FALSE}
 swInput <- reactive({
    # Race Filter
    if (length(input$SelectedRace) > 0 ) {
      RaceAgeGender.server <- subset(RaceAgeGender, Race %in% input$SelectedRace)
    }
    
    return( RaceAgeGender.server)
  })
```

Map
=====================================


```{r }
output$mymap <- renderLeaflet({
leaflet()%>% 
  setView(-73.87300,  40.72, zoom = 10) %>%
   addProviderTiles("OpenStreetMap.HOT", options = providerTileOptions(noWrap = TRUE)) %>% 
  addMarkers(data = AccidInput(), lng = ~as.numeric(as.character(longitude)), lat = ~as.numeric(as.character(latitude)), clusterOptions = markerClusterOptions(), popup = ~contributing_factor_vehicle_1, label = ~contributing_factor_vehicle_1,  group = "Accidents") %>% 
addHeatmap(data = AccidInput(), lng = ~as.numeric(as.character(longitude)), lat = ~as.numeric(as.character(latitude)), radius = 8, group = "Heat Map") %>% 
  addLayersControl( overlayGroups = c("Accidents",  "Heat Map"),
    options = layersControlOptions(collapsed = FALSE))
  })
leafletOutput("mymap")
```

Accident Charts
=====================================

Row 
-------------------------------------
```{r}
#A plot of the number of critical violations per inspection date
  output$accidHours <- renderPlotly({
    data1 <- AccidInput()@data
    data1$time <- hms(as.character(data1$time))
    data1$hour <- data1$time@hour
    data2 <- data1 %>% group_by(hour) %>% summarise(injured = sum(as.numeric(as.character(number_of_motorist_injured))))
    ggplotly(
      ggplot(data = data2, mapping = aes(x=hour, y=injured))+
        geom_line() +
        labs(x="Time of Day (24 hours)", y="Number of Injuries"))
  })

plotlyOutput("accidHours")

```


Row 
-------------------------------------
```{r}
#A plot of the number of critical violations per inspection date
  output$accidBoro <- renderPlotly({
    data3 <-  AccidInput()@data
    data3 <- data3 %>% count(borough)
    ggplotly(
      ggplot(data = data3, mapping = aes(x=borough, y=n))+
         geom_bar(stat="identity") +
        labs(x="New York City Boroughs", y="Number of Accidents"))
  })

plotlyOutput("accidBoro")

```

Raw Data
=====================================

Row 
-------------------------------------


```{r }
  #Output the Data Table
  output$table <- DT::renderDataTable({
    AccidentData <- subset(AccidInput()@data, select = c(date, time, borough, latitude, longitude,contributing_factor_vehicle_1, number_of_motorist_injured, number_of_cyclist_killed, number_of_pedestrians_killed, number_of_motorist_killed))

  })
  

dataTableOutput("table")
  


```

